Repository moonshine-software/moonshine, pull requests merged in 2025-03, with the labels that each got.

#1642 feat: TextWrap
  src/Contracts/src/UI/FieldContract.php
  src/Support/src/Enums/TextWrap.php
  src/UI/src/Fields/Field.php
  src/UI/src/Fields/Password.php
  src/UI/src/Fields/Text.php
  src/UI/src/Fields/Textarea.php
  src/UI/src/Fields/Url.php
  tests/Unit/Fields/TextFieldTest.php
Labels: ready for merge, documented

#1633 feat: stop filtering json + number/checkbox cast
  src/UI/src/Fields/Checkbox.php
  src/UI/src/Fields/Json.php
  src/UI/src/Fields/Number.php
  tests/Unit/Fields/CheckboxFieldTest.php
  tests/Unit/Fields/NumberFieldTest.php
  tests/Unit/Fields/SwitcherFieldTest.php
Labels: ready for merge, documented

#1644 feat: HtmlMode parameter to html() method
  src/Laravel/src/Http/Responses/MoonShineJsonResponse.php
  src/UI/resources/js/Request/Core.js
  src/UI/resources/js/Support/HtmlMode.js
  src/UI/src/Enums/HtmlMode.php
Labels: ready for merge

#1628 feat: Refresh after apply
  src/Contracts/src/Core/DependencyInjection/FieldsContract.php
  src/Contracts/src/UI/FormElementContract.php
  src/Laravel/src/Http/Controllers/CrudController.php
  src/UI/resources/js/Request/Core.js
  src/UI/resources/js/Support/HtmlMode.js
  src/UI/resources/views/components/form/file.blade.php
  src/UI/src/Collections/Fields.php
  src/UI/src/Fields/Field.php
  src/UI/src/Fields/File.php
  src/UI/src/Traits/Fields/Applies.php
Labels: documented, waiting pr

#1651 feat: Toast duration time
  src/Laravel/src/Http/Responses/MoonShineJsonResponse.php
  src/Laravel/src/MoonShineUI.php
  src/Support/src/ToastEventParams.php
  src/UI/resources/js/Components/FormBuilder.js
  src/UI/resources/js/Components/Toast.js
  src/UI/resources/js/Request/Core.js
  src/UI/resources/js/Support/UI.js
  src/UI/resources/js/__tests__/Request/Core.test.js
  src/UI/resources/js/moonshine.js
  src/UI/resources/views/components/layout/flash.blade.php
  src/UI/resources/views/components/toast.blade.php
  src/UI/resources/views/shared/toasts.blade.php
Labels: ready for merge
